# Generated by Django 3.2.4 on 2022-05-16 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 16, 4, 55, 25, 176033, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
